---
title: "Factor analysis between-person"
author: "Anne Margit"
date: "6/8/2020"
output: github_document
---

This is the confirmatory factor analysis of between-person emotion scores (i.e., mean scores across waves)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packagages, include=FALSE}
library(psych)
library(dplyr)
library(tidyverse)
library(lavaan)  
library(ggplot2)
library(corrplot)
library(knitr)
```

```{r, results = "hide"}
load("data_long_min3.Rdata")
```

```{r, results = "hide"}
data_long_min3 <- as_tibble(data_long_min3)
data_factor <- data_long_min3 %>% select(X, Wave, Ang, Anxiety, Bored, Calm, Content, Depr, Energ, Exc, Exh, Insp, Lov, Nerv, Rel)
  
```

```{r, results = "hide"}
data_means <- data_factor %>%
    dplyr::group_by(X) %>%
    dplyr::summarise_each(funs(mean(., na.rm=TRUE)), 
                          Ang, Anxiety, Bored, Calm, Content, Depr, Energ, Exc, Exh, Insp, Lov, Nerv, Rel)
```


```{r}
round(cor(data_means[,c("Ang", "Anxiety", "Bored", "Depr","Exh","Nerv","Calm", "Content","Energ","Exc", "Insp", "Lov","Rel")],use= "complete.obs"),2)
```

```{r}
corrplot(cor(data_means[,c("Ang", "Anxiety", "Bored", "Depr","Exh","Nerv","Calm", "Content","Energ","Exc", "Insp", "Lov","Rel")], use="complete.obs"), order = "original", tl.col='black', tl.cex=.75)
```

```{r, results = "hide"}
model <- '
f1 =~ Ang + Anxiety + Bored + Depr + Exh + Nerv 
f2 =~ Calm + Content + Energ + Exc + Insp + Lov + Rel 

# latent variable variances
f1 ~~ 1*f1
f2 ~~ 1*f2

# latent variable covariances
f1 ~~ f2

# manifest variable variances (uniquenesses)
  Ang ~~ Ang
  Anxiety ~~ Anxiety
  Bored ~~ Bored
  Depr ~~ Depr
  Exh ~~ Exh
  Nerv ~~ Nerv
  Calm ~~ Calm
  Content ~~ Content
  Energ ~~ Energ
  Exc ~~ Exc
  Insp ~~ Insp
  Lov ~~ Lov
  Rel ~~ Rel

#manifest variable means 
  Ang ~ 1
  Anxiety ~ 1
  Bored ~ 1
  Depr ~ 1
  Exh ~ 1
  Nerv ~ 1
  Calm ~ 1
  Content ~ 1
  Energ ~ 1
  Exc ~ 1
  Insp ~ 1
  Lov ~ 1
  Rel ~ 1
'
```

```{r}
fit <- cfa(model, data = data_means, std.lv=TRUE, missing="fiml")
summary(fit, standardized=TRUE, fit.measures=TRUE)
```

```{r}
parameterEstimates(fit, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Factor Loadings")
```

```{r}

```