---
title: "CFA Multi-level cfa without bored and loved"
author: "Anne Margit"
date: "18/8/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packagages, include=FALSE, warning=FALSE}
library(psych)
library(dplyr)
library(tidyverse)
library(lavaan)  
library(ggplot2)
library(corrplot)
library(knitr)
library(papaja)
```

```{r, results = "hide"}
load(file = "data_long_min3_str.Rdata")
```

Without Content, Excited, Loved, Bored
```{r, results = "hide"}
data_long_min3_str <- as_tibble(data_long_min3_str)
data_cfa_red <- data_long_min3_str %>% select(ID, Wave, Country, Ang, Anxiety, Calm, Depr, Energ, Exh, Insp, Nerv, Rel)
```

```{r, results = "hide"}
data_country_means <- data_cfa_red %>%
    dplyr::group_by(Country) %>%
    dplyr::summarise_each(funs(mean(., na.rm=TRUE)), 
                          Ang, Anxiety, Calm, Depr, Energ, Exh, Insp, Nerv, Rel)
```

```{r}
apa_table(data_country_means)
```

```{r, results = "hide"}
data_cfa_comb <- left_join(data_cfa_red, data_country_means, by="Country")
```

This dataframe data_within contains the raw scores - country means

```{r, results = "hide"}
data_cfa_new <- data_cfa_comb %>%
group_by(ID) %>%
  transmute(Wave = Wave,
            Country = Country,
    Ang = Ang.x - Ang.y,
         Anxiety = Anxiety.x - Anxiety.y,
         Calm = Calm.x - Calm.y,
         Depr = Depr.x - Depr.y,
         Energ = Energ.x - Energ.y,
         Exh = Exh.x - Exh.y,
         Insp = Insp.x - Insp.y,
         Nerv = Nerv.x - Nerv.y,
         Rel = Rel.x - Rel.y)
```

```{r}
save(data_cfa_new,file ="data_cfa_new.Rdata")
```

```{r}
round(cor(data_cfa_new[,c("Ang", "Anxiety", "Depr","Exh","Nerv","Calm","Energ", "Insp","Rel")],use= "pairwise.complete.obs"),2)
```

```{r}
corrplot(cor(data_cfa_new[,c("Ang", "Anxiety", "Depr","Exh","Nerv","Calm","Energ", "Insp","Rel")], use="pairwise.complete.obs"), order = "original", tl.col='black', tl.cex=.75)
```

Two-factor CFA without loved and bored

```{r, results = "hide"}
model2 <- '
level: 1
f1 =~ Ang + Anxiety + Depr + Exh + Nerv 
f2 =~ Calm + Energ + Insp + Rel 

level: 2
f1 =~ Ang + Anxiety + Depr + Exh + Nerv 
f2 =~ Calm + Energ + Insp + Rel 
'
```

```{r, results = "hide", warning = FALSE}
fit2 <- cfa(model2, data = data_cfa_new, std.lv=TRUE, missing="fiml", cluster = "ID", estimator = "MLR")
```

```{r}
summary(fit2, standardized=TRUE, fit.measures=TRUE)
```

```{r}
parameterEstimates(fit2, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Factor Loadings")
```


```{r}
summary(fit2, standardized=TRUE, fit.measures=TRUE)
```
```{r}
parameterEstimates(fit2, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Factor Loadings")
```

Three-factor CFA without loved and bored centered around country means. 

```{r, results = "hide"}
model3 <- '
level: 1
f1 =~ Ang + Anxiety + Nerv + Depr + Exh
f2 =~ Energ + Insp
f3 =~ Calm + Rel

level: 2
f1 =~ Ang + Anxiety + Nerv + Depr + Exh
f2 =~ Energ + Insp
f3 =~ Calm + Rel
'
```

```{r, results = "hide", warning = FALSE}
fit3 <- cfa(model3, data = data_cfa_new, std.lv=TRUE, missing="fiml", cluster = "ID", estimator = "MLR")
```

```{r}
summary(fit3, standardized=TRUE, fit.measures=TRUE)
```

```{r}
parameterEstimates(fit3, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Factor Loadings")
```


Four-factor CFA without loved centered around country means

```{r, results = "hide"}
model4 <- '
level: 1
f1 =~ Ang + Anxiety + Nerv 
f2 =~ Depr + Exh
f3 =~ Energ + Insp
f4 =~ Calm + Rel

level: 2
f1 =~ Ang + Anxiety + Nerv 
f2 =~ Depr + Exh
f3 =~ Energ + Insp
f4 =~ Calm + Rel
'
```

```{r, results = "hide", warning = FALSE}
fit4 <- cfa(model4, data = data_cfa_new, std.lv=TRUE, missing="fiml", cluster = "ID", estimator = "MLR")
```

```{r}
summary(fit4, standardized=TRUE, fit.measures=TRUE)
```

```{r}
parameterEstimates(fit4, standardized=TRUE) %>% 
  filter(op == "=~") %>% 
  select('Latent Factor'=lhs, Indicator=rhs, B=est, SE=se, Z=z, 'p-value'=pvalue, Beta=std.all) %>% 
  kable(digits = 3, format="pandoc", caption="Factor Loadings")
```

