---
title: "HGis data analysis"
author: "Anne Margit"
date: "10/29/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("data_HGis.Rdata")
```
```{r, message=F}
library(dplyr)
library(tidyverse)
library(psych)
library(lme4)
library(lmerTest)
```

Sample size per age group
```{r}
data_HGis$Age_new <- as.factor(data_HGis$Age_new)

data_HGis %>% 
group_by(Age_new) %>%
summarize(NAge = n())
```

Mean emotion ratings + sd per timepoint
```{r}
data_HGis %>% 
group_by(Time) %>% 
summarise_at(
  .vars = vars(NAA, NAD, PAA),
  .funs = c(mean="mean", sd="sd"), na.rm=TRUE)
```

Means per age group per timepoint
```{r}
data_HGis %>% 
group_by(Age_new, Time) %>% 
summarise_at(
  .vars = vars(NAA, NAD, PAA),
  .funs = c(mean="mean", sd="sd"), na.rm=TRUE)
```

NAA
```{r}
lmer_NAA <- lmer(NAA ~ Time + Age_new + (1|profile_id), data=data_HGis)
summary(lmer_NAA)
anova(lmer_NAA)
```
NAD
```{r}
lmer_NAD <- lmer(NAD ~ Time + Age_new + (1|profile_id), data=data_HGis)
summary(lmer_NAD)
anova(lmer_NAD)
```

PAA
```{r}
lmer_PAA <- lmer(PAA ~ Time + Age_new + (1|profile_id), data=data_HGis)
summary(lmer_PAA)
anova(lmer_PAA)
```




