---
title: "Difference scores phase 2 heatmaps"
author: "Anne Margit"
date: "02/04/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, set-options, echo=FALSE, cache= FALSE}
options(width=1000)
Sys.getenv('R_MAX_VSIZE')
```

```{r, results = "hide"}
load("data_analyse2_p1.Rdata")
load("data_analyse2_p2.Rdata")
load("data_analyse2_p3.Rdata")
```

```{r, message=F}
library(dplyr)
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(rockchalk)
library(effects)
library(nlme)
library(lattice)
library(broom.mixed)
library(purrr)
library(stargazer)
```

```{r, message=F}
#Create variable that indicates first day of max stringency (0) and last day (1) in period
data_analyse2_p2$Time <- as.numeric(data_analyse2_p2$Time)

data_analyse2_p2 <- data_analyse2_p2 %>% 
  group_by(ID) %>%
  mutate(Day = ifelse(DaysMax == min(DaysMax) & Time==min(Time), 0, 
                      ifelse(DaysMax == max(DaysMax) & Time ==max(Time), 1, NA)))

# Filter observations that are either on the first or last day
data_analyse_p2_select <- data_analyse2_p2 %>%
  ungroup()%>%
  filter(Day==0 | Day == 1)

# Add number of measurements per ID (nn)
data_analyse_p2_select <- data_analyse_p2_select %>% group_by(ID) %>% add_tally()

#Select pps with at least 2 measurements in this period (otherwise no diff score is possible)
data_analyse_p2_select <- data_analyse_p2_select %>%
  subset(nn > 1)

# Order data
data_analyse_p2_select <- data_analyse_p2_select[with(data_analyse_p2_select, order(Country, ID, Time)),]

# Create lag 
data_analyse_p2_select <- data_analyse_p2_select %>%
  group_by(ID)%>%
  mutate(NAA_L = lead(NAA, n=1L))

data_analyse_p2_select <- data_analyse_p2_select %>%
  group_by(ID)%>%
  mutate(NAD_L = lead(NAD, n=1L))

data_analyse_p2_select <- data_analyse_p2_select %>%
  group_by(ID)%>%
  mutate(PAA_L = lead(PAA, n=1L))

data_analyse_p2_select <- data_analyse_p2_select %>%
  group_by(ID)%>%
  mutate(PAD_L = lead(PAD, n=1L))

# Create difference score
data_analyse_p2_select <- data_analyse_p2_select %>%
  ungroup()%>%
  mutate(NAA_diff = NAA_L - NAA)

data_analyse_p2_select <- data_analyse_p2_select %>%
  ungroup()%>%
  mutate(NAD_diff = NAD_L - NAD)

data_analyse_p2_select <- data_analyse_p2_select %>%
  ungroup()%>%
  mutate(PAA_diff = PAA_L - PAA)

data_analyse_p2_select <- data_analyse_p2_select %>%
  ungroup()%>%
  mutate(PAD_diff = PAD_L - PAD)

data_analyse_p2_diff <- data_analyse_p2_select
```

Heatmap NAA
Order
```{r, message = F}
data_analyse_p2_diff <- data_analyse_p2_diff[with(data_analyse_p2_diff, order(ID)),]

data_analyse_p2_diff2 <- data_analyse_p2_diff %>%
  filter(!is.na(NAA_diff))

data_analyse_p2_diff2$NAA_diff <- round(data_analyse_p2_diff2$NAA_diff, digits = 2)
data_analyse_p2_diff2$NAD_diff <- round(data_analyse_p2_diff2$NAD_diff, digits = 2)
data_analyse_p2_diff2$PAA_diff <- round(data_analyse_p2_diff2$PAA_diff, digits = 2)
data_analyse_p2_diff2$PAD_diff <- round(data_analyse_p2_diff2$PAD_diff, digits = 2)

```


```{r, message = F}
data_analyse_p2_diff2$Age <- as.numeric(data_analyse_p2_diff2$Age)

#Density plot
p_NAA <- ggplot(data_analyse_p2_diff2, aes(x = NAA_diff, fill = Age_new)) +
  geom_density(alpha=0.2, adjust=1) +
  facet_wrap(.~ Age_new)

#Histogram
Age_labels <- c("18-24", "25-44", "45-64", "65+")
names(Age_labels) <- c("0","1","2","3")

p_NAA <- ggplot(data_analyse_p2_diff2, aes(x= NAA_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  facet_wrap(.~ Age_new, labeller = labeller(Age_new = Age_labels)) +
  theme_minimal()+
  theme(legend.position="none") +
  labs(title="NAA difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count")
  
  
#Histogram with line for mean difference score per age group
vline_df <- data.frame(Age_new = levels(data_analyse_p2_diff2$Age_new),
                       Means = tapply(X = data_analyse_p2_diff2$NAA_diff, INDEX = data_analyse_p2_diff2$Age_new,
                                        FUN = mean))

p_NAA2 <- ggplot(data_analyse_p2_diff2, aes(x= NAA_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  theme_minimal()+
  theme(legend.position="none") + 
  labs(title="NAA difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count") +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_vline(data = vline_df, aes(xintercept=Means), linetype="dashed", color="red") +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) 

```
```{r, message = F}
p_NAA
p_NAA2
```

NAD
```{r, message = F}
data_analyse_p2_diff2$Age <- as.numeric(data_analyse_p2_diff2$Age)

#Density plot
p_NAD <- ggplot(data_analyse_p2_diff2, aes(x = NAD_diff, fill = Age_new)) +
  geom_density(alpha=0.4) +
  facet_wrap(.~ Age_new)

#Histogram
p_NAD <- ggplot(data_analyse_p2_diff2, aes(x= NAD_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  facet_wrap(.~ Age_new, labeller = labeller(Age_new = Age_labels)) +
  theme_minimal()+
  theme(legend.position="none") +
  labs(title="NAD difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count")
  
#Histogram with line for mean difference score per age group
vline_df <- data.frame(Age_new = levels(data_analyse_p2_diff2$Age_new),
                       Means = tapply(X = data_analyse_p2_diff2$NAD_diff, INDEX = data_analyse_p2_diff2$Age_new,
                                        FUN = mean))

p_NAD2 <- ggplot(data_analyse_p2_diff2, aes(x= NAD_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  theme_minimal()+
  theme(legend.position="none") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title="NAD difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count") +
  geom_vline(data = vline_df, aes(xintercept=Means), linetype="dashed", color="red") +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) 

```
```{r, message = F}
p_NAD
p_NAD2
```

PAA
```{r, message = F}
data_analyse_p2_diff2$Age <- as.numeric(data_analyse_p2_diff2$Age)

#Density plot
p_PAA <- ggplot(data_analyse_p2_diff2, aes(x = PAA_diff, fill = Age_new)) +
  geom_density(alpha=0.4) +
  facet_wrap(.~ Age_new)

#Histogram
p_PAA <- ggplot(data_analyse_p2_diff2, aes(x= PAA_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) +
  theme_minimal()+
  theme(legend.position="none") +
  labs(title="PAA difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count")
  
  
#Histogram with line for mean difference score per age group
vline_df <- data.frame(Age_new = levels(data_analyse_p2_diff2$Age_new),
                       Means = tapply(X = data_analyse_p2_diff2$PAA_diff, INDEX = data_analyse_p2_diff2$Age_new,
                                        FUN = mean))

p_PAA2 <- ggplot(data_analyse_p2_diff2, aes(x= PAA_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  theme_minimal()+
  theme(legend.position="none") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title="PAA difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count") +
  geom_vline(data = vline_df, aes(xintercept=Means), linetype="dashed", color="red") +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) 
```

```{r, message = F}
p_PAA
p_PAA2
```

PAD
```{r, message = F}
data_analyse_p2_diff2$Age <- as.numeric(data_analyse_p2_diff2$Age)

#Density plot
p_PAD <- ggplot(data_analyse_p2_diff2, aes(x = PAD_diff, fill = Age_new)) +
  geom_density(alpha=0.4) +
  facet_wrap(.~ Age_new)

#Histogram
p_PAD <- ggplot(data_analyse_p2_diff2, aes(x= PAD_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) +
  theme_minimal()+
  theme(legend.position="none") +
  labs(title="PAD difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count")
  
  
#Histogram with line for mean difference score per age group
vline_df <- data.frame(Age_new = levels(data_analyse_p2_diff2$Age_new),
                       Means = tapply(X = data_analyse_p2_diff2$PAD_diff, INDEX = data_analyse_p2_diff2$Age_new,
                                        FUN = mean))

p_PAD2 <- ggplot(data_analyse_p2_diff2, aes(x= PAD_diff,  fill = ..x..)) +
  geom_histogram(binwidth = 0.5) +
  scale_fill_gradientn(colours = terrain.colors(5)) +
  theme_minimal()+
  theme(legend.position="none") + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(title="PAD difference scores during peak stringency (end - start) in each age group",
       x="Difference scores", y = "Count") +
  geom_vline(data = vline_df, aes(xintercept=Means), linetype="dashed", color="red") +
  facet_wrap(~ Age_new, labeller = labeller(Age_new = Age_labels)) 
```


```{r, message = F}
p_PAD
p_PAD2
```


```{r, message=F}
save(data_analyse_p2_diff, file = 'data_analyse_p2_diff.Rdata')
```


